wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 4096
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692928912.856963
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.8.10
      5: 0.15.8
      8:
      - 5
